import React, { Component } from 'react';
import Select from 'react-select';
import { Button } from 'mdbreact'

/* const symptoms = [
{ value: 'Abnormalities of Cardiac cycle|heart beat', label: 'Abnormalities of Cardiac cycle|heart beat' },
{ value: 'Tachycardia, unspecified', label: 'Tachycardia, unspecified' },
{ value: 'Bradycardia, unspecified', label: 'Bradycardia, unspecified' },
{ value: 'Palpitations', label: 'Palpitations' },
{ value: 'Other and unspecified abnormalities of Cardiac cycle|heart beat', label: 'Other and unspecified abnormalities of Cardiac cycle|heart beat' },
{ value: 'Cardiac murmurs and other cardiac sounds', label: 'Cardiac murmurs and other cardiac sounds' },
{ value: 'Benign and innocent cardiac murmurs', label: 'Benign and innocent cardiac murmurs' },
{ value: 'Cardiac murmur, unspecified', label: 'Cardiac murmur, unspecified' },
{ value: 'Cardiac bruit NOS', label: 'Cardiac bruit NOS' },
{ value: 'Other cardiac sounds', label: 'Other cardiac sounds' },
{ value: 'Gangrene, not elsewhere classified', label: 'Gangrene, not elsewhere classified' },
{ value: 'Abnormal blood-pressure reading, without diagnosis', label: 'Abnormal blood-pressure reading, without diagnosis' },
{ value: 'Elevated blood-pressure reading, without diagnosis of hypertension', label: 'Elevated blood-pressure reading, without diagnosis of hypertension' },
{ value: 'Nonspecific low blood-pressure reading', label: 'Nonspecific low blood-pressure reading' },
{ value: 'Haemorrhage from respiratory passages', label: 'Haemorrhage from respiratory passages' },
{ value: 'Epistaxis', label: 'Epistaxis' },
{ value: 'Haemorrhage from throat', label: 'Haemorrhage from throat' },
{ value: 'Haemoptysis', label: 'Haemoptysis' },
{ value: 'Haemorrhage from other sites in respiratory passages', label: 'Haemorrhage from other sites in respiratory passages' },
{ value: 'Haemorrhage from respiratory passages, unspecified', label: 'Haemorrhage from respiratory passages, unspecified' },
{ value: 'Cough', label: 'Cough' },
{ value: 'Abnormalities of breathing', label: 'Abnormalities of breathing' },
{ value: 'Dyspnoea', label: 'Dyspnoea' },
{ value: 'Orthopnoea', label: 'Orthopnoea' },
{ value: 'Stridor', label: 'Stridor' },
{ value: 'Wheezing', label: 'Wheezing' },
{ value: 'Periodic breathing', label: 'Periodic breathing' },
{ value: 'Cheyne-Stokes respiration', label: 'Cheyne-Stokes respiration' },
{ value: 'Hyperventilation', label: 'Hyperventilation' },
{ value: 'Mouth breathing', label: 'Mouth breathing' },
{ value: 'Snoring', label: 'Snoring' },
{ value: 'Hiccup', label: 'Hiccup' },
{ value: 'Sneezing', label: 'Sneezing' },
{ value: 'Other and unspecified abnormalities of breathing', label: 'Other and unspecified abnormalities of breathing' },
{ value: 'Choking sensation', label: 'Choking sensation' },
{ value: 'Pain and nociception|Pain in throat and chest', label: 'Pain and nociception|Pain in throat and chest' },
{ value: 'Pain in throat', label: 'Pain in throat' },
{ value: 'Chest pain on breathing', label: 'Chest pain on breathing' },
{ value: 'Precordial pain', label: 'Precordial pain' },
{ value: 'Other chest pain', label: 'Other chest pain' },
{ value: 'Chest pain, unspecified', label: 'Chest pain, unspecified' },
{ value: 'Other symptoms and signs involving the circulatory and respiratory systems', label: 'Other symptoms and signs involving the circulatory and respiratory systems' },
{ value: 'Asphyxia', label: 'Asphyxia' },
{ value: 'Pleurisy', label: 'Pleurisy' },
{ value: 'Respiratory arrest', label: 'Respiratory arrest' },
{ value: 'Abnormal sputum', label: 'Abnormal sputum' },
{ value: 'Other specified symptoms and signs involving the circulatory and respiratory systems', label: 'Other specified symptoms and signs involving the circulatory and respiratory systems' },
{ value: 'Rales', label: 'Rales' },
{ value: 'Arterial Bruit', label: 'Arterial Bruit' },
{ value: 'Abdominal and pelvic pain', label: 'Abdominal and pelvic pain' },
{ value: 'Acute abdomen', label: 'Acute abdomen' },
{ value: 'Pain localized to upper abdomen', label: 'Pain localized to upper abdomen' },
{ value: 'Pelvic pain|Pelvic and perineal pain', label: 'Pelvic pain|Pelvic and perineal pain' },
{ value: 'Pain localized to other parts of lower abdomen', label: 'Pain localized to other parts of lower abdomen' },
{ value: 'Other and unspecified abdominal pain', label: 'Other and unspecified abdominal pain' },
{ value: 'Abdominal tenderness NOS', label: 'Abdominal tenderness NOS' },
{ value: 'Colic, NOS', label: 'Colic, NOS' },
{ value: 'infantile colic', label: 'infantile colic' },
{ value: 'Nausea and vomiting', label: 'Nausea and vomiting' },
{ value: 'Heartburn', label: 'Heartburn' },
{ value: 'Dysphagia', label: 'Dysphagia' },
{ value: 'Flatulence and related conditions', label: 'Flatulence and related conditions' },
{ value: 'Abdominal distension (gaseous)', label: 'Abdominal distension (gaseous)' },
{ value: 'Bloating', label: 'Bloating' },
{ value: 'Eructation', label: 'Eructation' },
{ value: 'Gas pain', label: 'Gas pain' },
{ value: 'Tympanites (abdominal)(intestinal)', label: 'Tympanites (abdominal)(intestinal)' },
{ value: 'Faecal incontinence', label: 'Faecal incontinence' },
{ value: 'Encopresis', label: 'Encopresis' },
{ value: 'Hepatomegaly and splenomegaly, not elsewhere classified', label: 'Hepatomegaly and splenomegaly, not elsewhere classified' },
{ value: 'Hepatomegaly, not elsewhere classified', label: 'Hepatomegaly, not elsewhere classified' },
{ value: 'Splenomegaly, not elsewhere classified', label: 'Splenomegaly, not elsewhere classified' },
{ value: 'Hepatomegaly with splenomegaly, not elsewhere classified', label: 'Hepatomegaly with splenomegaly, not elsewhere classified' },
{ value: 'Hepatosplenomegaly NOS', label: 'Hepatosplenomegaly NOS' },
{ value: 'Unspecified jaundice', label: 'Unspecified jaundice' },
{ value: 'Ascites', label: 'Ascites' },
{ value: 'Other symptoms and signs involving the digestive system and abdomen', label: 'Other symptoms and signs involving the digestive system and abdomen' },
{ value: 'Intra-abdominal and pelvic swelling, mass and lump', label: 'Intra-abdominal and pelvic swelling, mass and lump' },
{ value: 'Abnormal bowel sounds', label: 'Abnormal bowel sounds' },
{ value: 'Visible peristalsis', label: 'Visible peristalsis' },
{ value: 'Abdominal rigidity', label: 'Abdominal rigidity' },
{ value: 'Change in bowel habit', label: 'Change in bowel habit' },
{ value: 'Other faecal abnormalities', label: 'Other faecal abnormalities' },
{ value: 'Halitosis', label: 'Halitosis' },
{ value: 'Other specified symptoms and signs involving the digestive system and abdomen', label: 'Other specified symptoms and signs involving the digestive system and abdomen' },
{ value: 'Disturbances of skin sensation', label: 'Disturbances of skin sensation' },
{ value: 'Anaesthesia of skin', label: 'Anaesthesia of skin' },
{ value: 'Hypoaesthesia of skin', label: 'Hypoaesthesia of skin' },
{ value: 'Paraesthesia of skin', label: 'Paraesthesia of skin' },
{ value: 'Hyperaesthesia', label: 'Hyperaesthesia' },
{ value: 'Other and unspecified disturbances of skin sensation', label: 'Other and unspecified disturbances of skin sensation' },
{ value: 'Rash and other nonspecific skin eruption', label: 'Rash and other nonspecific skin eruption' },
{ value: 'Localized Swelling (medical)|swelling, Mass (medicine)|mass and Swelling (medical)|lump of skin and subcutaneous tissue', label: 'Localized Swelling (medical)|swelling, Mass (medicine)|mass and Swelling (medical)|lump of skin and subcutaneous tissue' },
{ value: 'Localized swelling, mass and lump, head', label: 'Localized swelling, mass and lump, head' },
{ value: 'Localized swelling, mass and lump, neck', label: 'Localized swelling, mass and lump, neck' },
{ value: 'Localized swelling, mass and lump, trunk', label: 'Localized swelling, mass and lump, trunk' },
{ value: 'Localized swelling, mass and lump, upper limb', label: 'Localized swelling, mass and lump, upper limb' },
{ value: 'Localized swelling, mass and lump, lower limb', label: 'Localized swelling, mass and lump, lower limb' },
{ value: 'Localized swelling, mass and lump, multiple sites', label: 'Localized swelling, mass and lump, multiple sites' },
{ value: 'Localized swelling, mass and lump, unspecified', label: 'Localized swelling, mass and lump, unspecified' },
{ value: 'Other skin changes', label: 'Other skin changes' },
{ value: 'Cyanosis', label: 'Cyanosis' },
{ value: 'Pallor', label: 'Pallor' },
{ value: 'Flushing (physiology)|Flushing', label: 'Flushing (physiology)|Flushing' },
{ value: 'Spontaneous ecchymoses', label: 'Spontaneous ecchymoses' },
{ value: 'Petechiae', label: 'Petechiae' },
{ value: 'Changes in skin texture', label: 'Changes in skin texture' },
{ value: 'Desquamation', label: 'Desquamation' },
{ value: 'Induration', label: 'Induration' },
{ value: 'Other and unspecified skin changes', label: 'Other and unspecified skin changes' },
{ value: 'Abnormal involuntary movements', label: 'Abnormal involuntary movements' },
{ value: 'Abnormal head movements', label: 'Abnormal head movements' },
{ value: 'Tremor, unspecified', label: 'Tremor, unspecified' },
{ value: 'Cramp and spasm', label: 'Cramp and spasm' },
{ value: 'Fasciculation', label: 'Fasciculation' },
{ value: 'Other and unspecified abnormal involuntary movements', label: 'Other and unspecified abnormal involuntary movements' },
{ value: 'Gait abnormality|Abnormalities of gait and mobility', label: 'Gait abnormality|Abnormalities of gait and mobility' },
{ value: 'Ataxic gait', label: 'Ataxic gait' },
{ value: 'Paralytic gait', label: 'Paralytic gait' },
{ value: 'Difficulty in walking, not elsewhere classified', label: 'Difficulty in walking, not elsewhere classified' },
{ value: 'Other and unspecified abnormalities of gait and Motion (physics)|mobility', label: 'Other and unspecified abnormalities of gait and Motion (physics)|mobility' },
{ value: 'Other lack of coordination', label: 'Other lack of coordination' },
{ value: 'Ataxia, unspecified', label: 'Ataxia, unspecified' },
{ value: 'Other and unspecified lack of coordination', label: 'Other and unspecified lack of coordination' },
{ value: 'Other symptoms and signs involving the nervous system|nervous and musculoskeletal systems', label: 'Other symptoms and signs involving the nervous system|nervous and musculoskeletal systems' },
{ value: 'Tetany (medical sign)|Tetany', label: 'Tetany (medical sign)|Tetany' },
{ value: 'Meningismus', label: 'Meningismus' },
{ value: 'Abnormal reflex', label: 'Abnormal reflex' },
{ value: 'Hyperreflexia', label: 'Hyperreflexia' },
{ value: 'Abnormal posture', label: 'Abnormal posture' },
{ value: 'Clicking hip', label: 'Clicking hip' },
{ value: 'Other and unspecified symptoms and signs involving the nervous system|nervous and musculoskeletal systems', label: 'Other and unspecified symptoms and signs involving the nervous system|nervous and musculoskeletal systems' },
{ value: 'Pain associated with micturition', label: 'Pain associated with micturition' },
{ value: 'Dysuria', label: 'Dysuria' },
{ value: 'Vesical tenesmus', label: 'Vesical tenesmus' },
{ value: 'Painful micturition, unspecified', label: 'Painful micturition, unspecified' },
{ value: 'Unspecified haematuria', label: 'Unspecified haematuria' },
{ value: 'Unspecified urinary incontinence', label: 'Unspecified urinary incontinence' },
{ value: 'Retention of urine', label: 'Retention of urine' },
{ value: 'Anuria and oliguria', label: 'Anuria and oliguria' },
{ value: 'Polyuria', label: 'Polyuria' },
{ value: 'Nocturia', label: 'Nocturia' },
{ value: 'Urethral discharge', label: 'Urethral discharge' },
{ value: 'Other symptoms and signs involving the urinary system', label: 'Other symptoms and signs involving the urinary system' },
{ value: 'Extravasation of urine', label: 'Extravasation of urine' },
{ value: 'Other difficulties with micturition', label: 'Other difficulties with micturition' },
{ value: 'Extrarenal uraemia', label: 'Extrarenal uraemia' },
{ value: 'Other and unspecified symptoms and signs involving the urinary system', label: 'Other and unspecified symptoms and signs involving the urinary system' },
{ value: 'Somnolence, stupor and coma', label: 'Somnolence, stupor and coma' },
{ value: 'Somnolence', label: 'Somnolence' },
{ value: 'Stupor', label: 'Stupor' },
{ value: 'Coma, unspecified', label: 'Coma, unspecified' },
{ value: 'Other symptoms and signs involving cognitive functions and awareness', label: 'Other symptoms and signs involving cognitive functions and awareness' },
{ value: 'Disorientation, unspecified', label: 'Disorientation, unspecified' },
{ value: 'Anterograde amnesia', label: 'Anterograde amnesia' },
{ value: 'Retrograde amnesia', label: 'Retrograde amnesia' },
{ value: 'Other amnesia', label: 'Other amnesia' },
{ value: 'Other and unspecified symptoms and signs involving cognitive functions and awareness', label: 'Other and unspecified symptoms and signs involving cognitive functions and awareness' },
{ value: 'Dizziness and giddiness', label: 'Dizziness and giddiness' },
{ value: 'Vertigo (medical)|Vertigo NOS', label: 'Vertigo (medical)|Vertigo NOS' },
{ value: 'Disturbances of olfaction|smell and taste', label: 'Disturbances of olfaction|smell and taste' },
{ value: 'Anosmia', label: 'Anosmia' },
{ value: 'Parosmia', label: 'Parosmia' },
{ value: 'Parageusia', label: 'Parageusia' },
{ value: 'Other and unspecified disturbances of olfaction|smell and taste', label: 'Other and unspecified disturbances of olfaction|smell and taste' },
{ value: 'Other symptoms and signs involving general wikt:sensation|sensations and perceptions', label: 'Other symptoms and signs involving general wikt:sensation|sensations and perceptions' },
{ value: 'Auditory hallucinations', label: 'Auditory hallucinations' },
{ value: 'Visual hallucinations', label: 'Visual hallucinations' },
{ value: 'Other hallucinations', label: 'Other hallucinations' },
{ value: 'Hallucinations, unspecified', label: 'Hallucinations, unspecified' },
{ value: 'Other and unspecified symptoms and signs involving general wikt:sensation|sensations and perceptions', label: 'Other and unspecified symptoms and signs involving general wikt:sensation|sensations and perceptions' },
{ value: 'Symptoms and signs involving emotional state', label: 'Symptoms and signs involving emotional state' },
{ value: 'Anxiety|Nervousness', label: 'Anxiety|Nervousness' },
{ value: 'wikt:restlessness|Restlessness and wikt:restlessness|agitation', label: 'wikt:restlessness|Restlessness and wikt:restlessness|agitation' },
{ value: 'Unhappiness', label: 'Unhappiness' },
{ value: 'wikt:demoralization|Demoralization and apathy', label: 'wikt:demoralization|Demoralization and apathy' },
{ value: 'Irritability and anger', label: 'Irritability and anger' },
{ value: 'Hostility', label: 'Hostility' },
{ value: 'Physical violence', label: 'Physical violence' },
{ value: 'State of emotional shock and stress, unspecified', label: 'State of emotional shock and stress, unspecified' },
{ value: 'Other symptoms and signs involving emotional state', label: 'Other symptoms and signs involving emotional state' },
{ value: 'Suicidal ideation (tendencies)', label: 'Suicidal ideation (tendencies)' },
{ value: 'Symptoms and signs involving Human physical appearance|appearance and behaviour', label: 'Symptoms and signs involving Human physical appearance|appearance and behaviour' },
{ value: 'Very low level of personal hygiene', label: 'Very low level of personal hygiene' },
{ value: 'Bizarre personal appearance', label: 'Bizarre personal appearance' },
{ value: 'Strange and inexplicable behaviour', label: 'Strange and inexplicable behaviour' },
{ value: 'Overactivity', label: 'Overactivity' },
{ value: 'Slowness and poor responsiveness', label: 'Slowness and poor responsiveness' },
{ value: 'Suspiciousness and marked evasiveness', label: 'Suspiciousness and marked evasiveness' },
{ value: 'Undue concern and preoccupation with stressful events', label: 'Undue concern and preoccupation with stressful events' },
{ value: 'Verbosity and circumstantial detail obscuring reason for contact', label: 'Verbosity and circumstantial detail obscuring reason for contact' },
{ value: 'Other symptoms and signs involving Human physical appearance|appearance and behaviour', label: 'Other symptoms and signs involving Human physical appearance|appearance and behaviour' },
{ value: 'Speech disturbances, not elsewhere classified', label: 'Speech disturbances, not elsewhere classified' },
{ value: 'Dysphasia and aphasia', label: 'Dysphasia and aphasia' },
{ value: 'Dysarthria and anarthria', label: 'Dysarthria and anarthria' },
{ value: 'Other and unspecified speech disturbances', label: 'Other and unspecified speech disturbances' },
{ value: 'Dyslexia and other Symbolic dysfunctions, not elsewhere classified', label: 'Dyslexia and other Symbolic dysfunctions, not elsewhere classified' },
{ value: 'Dyslexia and alexia (condition)|alexia', label: 'Dyslexia and alexia (condition)|alexia' },
{ value: 'Agnosia', label: 'Agnosia' },
{ value: 'Apraxia', label: 'Apraxia' },
{ value: 'Other and unspecified Symbolic dysfunctions', label: 'Other and unspecified Symbolic dysfunctions' },
{ value: 'Acalculia', label: 'Acalculia' },
{ value: 'Agraphia', label: 'Agraphia' },
{ value: 'Voice disturbances', label: 'Voice disturbances' },
{ value: 'Dysphonia', label: 'Dysphonia' },
{ value: 'Aphonia', label: 'Aphonia' },
{ value: 'Hypernasality and hyponasality', label: 'Hypernasality and hyponasality' },
{ value: 'Other and unspecified voice disturbances', label: 'Other and unspecified voice disturbances' },
{ value: 'Fever of unknown origin', label: 'Fever of unknown origin' },
{ value: 'Fever with chills', label: 'Fever with chills' },
{ value: 'Persistent fever', label: 'Persistent fever' },
{ value: 'Fever, unspecified', label: 'Fever, unspecified' },
{ value: 'Headache', label: 'Headache' },
{ value: 'Pain and nociception|Pain, not elsewhere classified', label: 'Pain and nociception|Pain, not elsewhere classified' },
{ value: 'Pain and nociception|Acute pain', label: 'Pain and nociception|Acute pain' },
{ value: 'Chronic intractable pain', label: 'Chronic intractable pain' },
{ value: 'Other chronic pain', label: 'Other chronic pain' },
{ value: 'Pain and nociception|Pain, unspecified', label: 'Pain and nociception|Pain, unspecified' },
{ value: 'Malaise and fatigue (physical)|fatigue', label: 'Malaise and fatigue (physical)|fatigue' },
{ value: 'Asthenia NOS', label: 'Asthenia NOS' },
{ value: 'Debility (medical)|Debility NOS', label: 'Debility (medical)|Debility NOS' },
{ value: 'General physical deterioration', label: 'General physical deterioration' },
{ value: 'Lethargy', label: 'Lethargy' },
{ value: 'Tiredness', label: 'Tiredness' },
{ value: 'Senility', label: 'Senility' },
{ value: 'Vasovagal syncope|Syncope and Collapse (medical)|collapse', label: 'Vasovagal syncope|Syncope and Collapse (medical)|collapse' },
{ value: 'Convulsions, not elsewhere classified', label: 'Convulsions, not elsewhere classified' },
{ value: 'Febrile convulsions', label: 'Febrile convulsions' },
{ value: 'Other and unspecified convulsions', label: 'Other and unspecified convulsions' },
{ value: 'Physical fitness|Fit NOS', label: 'Physical fitness|Fit NOS' },
{ value: 'Seizure (convulsive) NOS', label: 'Seizure (convulsive) NOS' },
{ value: 'Shock (circulatory)|Shock, not elsewhere classified', label: 'Shock (circulatory)|Shock, not elsewhere classified' },
{ value: 'Cardiogenic shock', label: 'Cardiogenic shock' },
{ value: 'Hypovolaemic shock', label: 'Hypovolaemic shock' },
{ value: 'Other shock', label: 'Other shock' },
{ value: 'Shock, unspecified', label: 'Shock, unspecified' },
{ value: 'Haemorrhage, not elsewhere classified', label: 'Haemorrhage, not elsewhere classified' },
{ value: 'Enlarged lymph nodes', label: 'Enlarged lymph nodes' },
{ value: 'Localized enlarged lymph nodes', label: 'Localized enlarged lymph nodes' },
{ value: 'Generalized enlarged lymph nodes', label: 'Generalized enlarged lymph nodes' },
{ value: 'Lymphadenopathy NOS', label: 'Lymphadenopathy NOS' },
{ value: 'Oedema, not elsewhere classified', label: 'Oedema, not elsewhere classified' },
{ value: 'Localized oedema', label: 'Localized oedema' },
{ value: 'Peripheral edema', label: 'Peripheral edema' },
{ value: 'Generalized oedema', label: 'Generalized oedema' },
{ value: 'Oedema, unspecified', label: 'Oedema, unspecified' },
{ value: 'Hyperhidrosis', label: 'Hyperhidrosis' },
{ value: 'Localized hyperhidrosis', label: 'Localized hyperhidrosis' },
{ value: 'Generalized hyperhidrosis', label: 'Generalized hyperhidrosis' },
{ value: 'Hyperhidrosis, unspecified', label: 'Hyperhidrosis, unspecified' },
{ value: 'Night sweats', label: 'Night sweats' },
{ value: 'Lack of expected normal physiological development', label: 'Lack of expected normal physiological development' },
{ value: 'Delayed milestone', label: 'Delayed milestone' },
{ value: 'Other lack of expected normal physiological development', label: 'Other lack of expected normal physiological development' },
{ value: 'Failure to gain weight', label: 'Failure to gain weight' },
{ value: 'Failure to thrive', label: 'Failure to thrive' },
{ value: 'Infantilism (physiological disorder)|Infantilism NOS', label: 'Infantilism (physiological disorder)|Infantilism NOS' },
{ value: 'Lack of growth', label: 'Lack of growth' },
{ value: 'Physical retardation', label: 'Physical retardation' },
{ value: 'Lack of expected normal physiological development, unspecified', label: 'Lack of expected normal physiological development, unspecified' },
{ value: 'Symptoms and signs concerning food and fluid intake', label: 'Symptoms and signs concerning food and fluid intake' },
{ value: 'Anorexia (symptom)|Anorexia', label: 'Anorexia (symptom)|Anorexia' },
{ value: 'Polydipsia', label: 'Polydipsia' },
{ value: 'Polyphagia', label: 'Polyphagia' },
{ value: 'Feeding difficulties and mismanagement', label: 'Feeding difficulties and mismanagement' },
{ value: 'Abnormal weight loss', label: 'Abnormal weight loss' },
{ value: 'Abnormal weight gain', label: 'Abnormal weight gain' },
{ value: 'Other symptoms and signs concerning food and fluid intake', label: 'Other symptoms and signs concerning food and fluid intake' },
{ value: 'Cachexia', label: 'Cachexia' },
{ value: 'Other general symptoms and signs', label: 'Other general symptoms and signs' },
{ value: 'Hypothermia, not associated with low environmental temperature', label: 'Hypothermia, not associated with low environmental temperature' },
{ value: 'Nonspecific symptoms peculiar to infancy', label: 'Nonspecific symptoms peculiar to infancy' },
{ value: 'Dry mouth, unspecified', label: 'Dry mouth, unspecified' },
{ value: 'Nail clubbing|Clubbing of fingers', label: 'Nail clubbing|Clubbing of fingers' },
{ value: 'Other specified general symptoms and signs', label: 'Other specified general symptoms and signs' },
{ value: 'Unknown and unspecified causes of morbidit', label: 'Unknown and unspecified causes of morbidit' }
] */

const symptoms = [
    { value: 'cough', label: 'cough' },
    { value: 'cough with phlegm (white)', label: 'cough with phlegm (white)' },
    { value: 'persistent cough', label: 'persistent cough' },
    { value: 'chest cough', label: 'chest cough' },
    { value: 'coughing blood', label: 'coughing blood' },
    { value: 'cough with mucus (yellow)', label: 'cough with mucus (yellow)' },
    { value: 'cough with sputum', label: 'cough with sputum' },
    { value: 'sneezing', label: 'sneezing' },
    { value: 'wheezing', label: 'wheezing' },
    { value: 'back pain', label: 'back pain' },
    { value: 'abdomen pain', label: 'abdomen pain' },
    { value: 'painful joints', label: 'painful joints' },
    { value: 'leg pain', label: 'leg pain' },
    { value: 'neck pain', label: 'neck pain' },
    { value: 'chest pain', label: 'chest pain' },
    { value: 'pain under rib', label: 'pain under rib' },
    { value: 'painful urination', label: 'painful urination' },
    { value: 'headache', label: 'headache' },
    { value: 'migraine', label: 'migraine' },
    { value: 'frontal headache', label: 'frontal headache' },
    { value: 'headache on one side', label: 'headache on one side' },
    { value: 'head congestion', label: 'head congestion' },
    { value: 'blood in stool', label: 'blood in stool' },
    { value: 'blood in urine', label: 'blood in urine' },
    { value: 'bloody nose', label: 'bloody nose' },
    { value: 'bloody diarrhea', label: 'bloody diarrhea' },
    { value: 'blood pressure elevated', label: 'blood pressure elevated' },
    { value: 'bloodshot eyes', label: 'bloodshot eyes' },
    { value: 'finger/nail clubbing', label: 'finger/nail clubbing' },
    { value: 'sudden weight loss', label: 'sudden weight loss' },
    { value: 'sudden weight gain', label: 'sudden weight gain' },
    { value: 'feeling lethargic', label: 'feeling lethargic' },
    { value: 'seizures', label: 'seizures' },
    { value: 'heart burn', label: 'heart burn' },
    { value: 'heart palpitations', label: 'heart palpitations' },
    { value: 'heart pounding', label: 'heart pounding' },
    { value: 'heart pain', label: 'heart pain' },
    { value: 'pregnant', label: 'pregnant' },
    { value: 'elevated heart rate', label: 'elevated heart rate' },
    { value: 'skin rash', label: 'skin rash' },
    { value: 'skin redness', label: 'skin redness' },
    { value: 'skin dry', label: 'skin dry' },
    { value: 'skin peeling', label: 'skin peeling' },
    { value: 'skin tags', label: 'skin tags' },
    { value: 'tiredness', label: 'tiredness' },
    { value: 'stomach pain', label: 'stomach pain' },
    { value: 'stomach cramps', label: 'stomach cramps' },
    { value: 'stomach pain after eating', label: 'stomach pain after eating' },
    { value: 'stomach growl', label: 'stomach growl' },
    { value: 'stomach bloating', label: 'stomach bloating' },
    { value: 'sore throat', label: 'sore throat' },
    { value: 'persistent sore throat', label: 'persisten sore throat' },
    { value: 'sore tongue', label: 'sore tongue' },
    { value: 'sores in mouth', label: 'sores in mouth' },
    { value: 'sore muscles', label: 'sore muscles' },
    { value: 'extreme irritability', label: 'extreme irritability' },
    { value: 'extreme dizziness', label: 'extreme dizziness' },
    { value: 'extremity pain', label: 'extremity pain' },
    { value: 'extremeities cold', label: 'extremities cold' },
    { value: 'extreme irritability', label: 'extreme irritability' },
    { value: 'dizziness', label: 'dizziness' },
    { value: 'dizzy spells', label: 'dizzy spells' },
    { value: 'dizziness upon standing', label: 'dizziness upon standing' },
    { value: 'dizziness', label: 'dizz' },
    { value: 'black stools', label: 'black stools' },
    { value: 'black outs', label: 'black outs' },
    { value: 'black spots in vision', label: 'black spots in vision' },
    { value: 'black vomit', label: 'black vomit' },
    { value: 'black tongue', label: 'black tongue' },
    { value: 'night sweats', label: 'night sweats' },
    { value: 'night terrors', label: 'night terrors' },
]

class SymptomForm extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      value: null
    };
  }
  
  handleClick = () => {
    this.setValue(null);
    this.props.onAddItem(this.state.value)
  }
  
  setValue = val => {
    this.setState(prevState => ({
      value: val
    }));
  };
  
  handleChange = val => {
    this.setValue(val);
  };
  
  render() {
    return (
        <div>
        <Select value={this.state.value} options={symptoms} onChange={this.handleChange} isClearable={true} placeholder='What is bothering you today?'/>
        <Button size='sm' color="primary" onClick={this.handleClick}>Add Symptom</Button>
        </div>
    );
  }
}

export { SymptomForm };